graph_config:
  nodes:
    generate_answer:
      node_type: llm
      prompt:
        - system: |
            You are an assistant tasked with solving python coding problems. 
            If the user provides critique, respond with a revised answer of your previous attempts.
            Do NOT generate any conversational text or apologize if your previous answer was incorrect.
            Respond ONLY with the code for the question.
        - user: |
            {rephrased_text}
      model:
        name: gpt4o
        parameters:
          temperature: 0.1

    critique_answer:
      pre_process: tasks.mbpp.code_generation.task_executor.critique_answer_node_pre_process
      node_type: llm
      output_role: user
      prompt:
        - system: |
            You are a teacher grading a solution to a python coding problem. Generate critique and recommendations for the user's submission by using the provided test cases to ensure that the user provided solution is correct. Instructions:
            1. If the answer, including all the steps, is correct, respond with 'NO MORE FEEDBACK'. 
               Respond with 'NO MORE FEEDBACK' ONLY after the user has corrected all the steps. 
               DO NOT say 'NO MORE FEEDBACK' until user provided solution is completely correct.
            2. Do NOT provide the complete answer to the problem. Only provide useful feedback to help the user improve their solution.
            3. Address the user in second person using 'you' and 'your'.

            QUESTION: {prompt}
            
            TEST CASES: {test_list}
      model:
        name: gpt4o
        parameters:
          temperature: 1.0

  edges:
    - from: START
      to: generate_answer
    - from: generate_answer
      to: critique_answer
    - from: critique_answer
      condition: tasks.mbpp.code_generation.task_executor.should_continue
      path_map:
        END: END
        generate_answer: generate_answer
