[tool.poetry]
name = "GraSP"
version = "0.1.0"
description = "GRAph-oriented Synthetic data generation Pipeline"
authors = ["Gopal Sarda <gopal.sarda@servicenow.com>","Bidyapati Pradhan <bidyapati.pradhan@servicenow.com>", "Jishnu S Nair <jishnus.nair@servicenow.com>", "Surajit Dasgupta <surajit.dasgupta@servicenow.com>", "Vipul Mittal <vipul.mittal@servicenow.com>", "Omkar Anustoop <omkar.anustoop@servicenow.com>", "Amit Saha <amit.saha@servicenow.com>", "Sriram Puttagunta <sriram.puttagunta@servicenow.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.10.8"
datasets = "^3.0.1"
httpx = "^0.27.2"
httpx-sse = "^0.4.0"
huggingface-hub = "^0.25.1"
langchain-community = "^0.3.1"
langchain-core = "^0.3.8"
langchain-mistralai = "^0.2.0"
langgraph = "^0.6.2"
mistralai = "^1.1.0"
openai = "^1.51.0"
pyyaml = "^6.0.2"
transformers = "^4.45.1"
grandalf = "^0.8"
sentencepiece = "^0.2.0"
protobuf = "^5.28.2"
jinja2 = "^3.1.4"
pathvalidate = "^3.2.1"
ujson = "^5.10.0"
fasttext = "^0.9.2"
lexicalrichness = "^0.5.1"
torch = "^2.7.0"
pytest = "^8.4.0"
langchain-openai = "^0.3.24"
streamlit = "^1.46.0"
streamlit-agraph= "^0.0.45"
streamlit-autorefresh= "^1.0.1"
streamlit-flow-component= "^1.6.1"
soundfile = "^0.13.1"
ollama = "^0.5.1"
mlxtend = "^0.23.4"
pandarallel = "^1.6.5"
sentence-transformers = "^5.1.0"

[tool.poetry.group.dev.dependencies]
setuptools = "^75.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
