[build-system]
requires = ["setuptools>=75", "wheel", "build>=1.2.1"]
build-backend = "setuptools.build_meta"

[project]
name = "grasp"
version = "0.1.0"
description = "GRAph-oriented Synthetic data generation Pipeline library"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name = "Bidyapati Pradhan", email = "bidyapati.pradhan@servicenow.com"},
  {name = "Surajit Dasgupta", email = "surajit.dasgupta@servicenow.com"},
  {name = "Amit Kumar Saha", email = "amit.saha@servicenow.com"},
  {name = "Sriram Puttagunta", email = "sriram.puttagunta@servicenow.com"},
  {name = "Omkar Anustoop", email = "omkar.anustoop@servicenow.com"},
  {name = "Vipul Mittal", email = "vipul.mittal@servicenow.com"},
  {name = "Gopal Sarda", email = "gopal.sarda@servicenow.com"},
  {name = "Jishnu S Nair", email = "jishnus.nair@servicenow.com"},
]
maintainers = [
  { name = "GraSP Team", email = "grasp_team@servicenow.com" }
]
license = {text = "Apache-2.0"}
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
]

dependencies = [
  "aiohttp",
  "datasets",
  "httpx",
  "httpx-sse",
  "huggingface-hub",
  "langchain-community",
  "langchain-core",
  "langchain-mistralai",
  "langgraph",
  "mistralai",
  "openai",
  "PyYAML",
  "transformers",
  "grandalf",
  "sentencepiece",
  "protobuf",
  "Jinja2",
  "pathvalidate",
  "ujson",
  "fasttext",
  "lexicalrichness",
  "langchain-openai",
  "ollama",
  "torch",
  "mlxtend",
  "pandarallel",
  "sentence-transformers"
]

[project.optional-dependencies]
ui = [
  "streamlit",
  "streamlit-agraph",
  "streamlit-autorefresh",
  "streamlit-flow-component",
]
audio = ["soundfile"]
dev = ["pytest", "build", "twine"]

[project.scripts]
grasp = "grasp.cli:main"
grasp-tools = "grasp.tools_cli:main"

[project.urls]
Homepage = "https://github.com/ServiceNow/GraSP"
Issues = "https://github.com/ServiceNow/GraSP/issues"

[tool.setuptools]
packages = { find = { include = ["grasp*"], exclude = ["tests*", "docs*", "grasp_lib_examples*", "apps*"] } }

[tool.setuptools.package-data]
grasp = ["**/*.yaml", "**/*.yml", "**/*.jinja2", "**/*.j2", "**/*.json"]

# --- Poetry section (explicit, must duplicate dependencies) ---
[tool.poetry]
name = "grasp"
version = "0.1.0"
description = "GRAph-oriented Synthetic data generation Pipeline library"
authors = ["GraSP Team <grasp_team@servicenow.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ServiceNow/GraSP"
repository = "https://github.com/ServiceNow/GraSP"

[tool.poetry.dependencies]
python = ">=3.11"
aiohttp = "*"
datasets = "*"
httpx = "*"
httpx-sse = "*"
huggingface-hub = "*"
langchain-community = "*"
langchain-core = "*"
langchain-mistralai = "*"
langgraph = "*"
mistralai = "*"
openai = "*"
PyYAML = "*"
transformers = "*"
grandalf = "*"
sentencepiece = "*"
protobuf = "*"
Jinja2 = "*"
pathvalidate = "*"
ujson = "*"
fasttext = "*"
lexicalrichness = "*"
langchain-openai = "*"
ollama = "*"
torch = "*"
mlxtend = "*"
pandarallel = "*"
sentence-transformers = "*"

[tool.poetry.extras]
ui = ["streamlit", "streamlit-agraph", "streamlit-autorefresh", "streamlit-flow-component", "watchdog"]
audio = ["soundfile"]

[tool.poetry.group.dev.dependencies]
pytest = "*"
build = "*"
twine = "*"
