data_config:
  source:
    type: "hf"
    repo_id: "google-research-datasets/mbpp"
    config_name: "sanitized"
    split: ["train"]
    transformations:
      - transform: sygra.processors.data_transform.RenameFieldsTransform
        params:
          mapping:
            task_id: id

graph_config:
  nodes:
    generate_question:
      node_type: subgraph
      subgraph: tasks.examples.custom_subgraphs.generate_question_subgraph
      node_config_map:
        paraphrase_question:
            output_keys: rephrased_text
            prompt_placeholder_map:
              p: prompt
            model:
                name: gpt-4o
                parameters:
                  temperature: 1.0

    generate_answer:
      node_type: llm
      prompt:
        - system: |
            You are an assistant tasked with solving python coding problems. 
            If the user provides critique, respond with a revised answer of your previous attempts.
            Do NOT generate any conversational text or apologize if your previous answer was incorrect.
            Respond ONLY with the code for the question.
        - user: |
            {rephrased_text}
      model:
        name: gpt-4o
        parameters:
          temperature: 0.1

    critique_answer:
      pre_process: tasks.examples.custom_subgraphs.task_executor.CritiqueAnswerNodePreProcessor
      node_type: llm
      output_role: user
      prompt:
        - system: |
            You are a teacher grading a solution to a python coding problem. Generate critique and recommendations for the user's submission by using the provided test cases to ensure that the user provided solution is correct. Instructions:
            1. If the answer, including all the steps, is correct, respond with 'NO MORE FEEDBACK'. 
               Respond with 'NO MORE FEEDBACK' ONLY after the user has corrected all the steps. 
               DO NOT say 'NO MORE FEEDBACK' until user provided solution is completely correct.
            2. Do NOT provide the complete answer to the problem. Only provide useful feedback to help the user improve their solution.
            3. Address the user in second person using 'you' and 'your'.

            QUESTION: {prompt}
            
            TEST CASES: {test_list}
      model:
        name: gpt-4o
        parameters:
          temperature: 1.0

  edges:
    - from: START
      to: generate_question
    - from: generate_question
      to: generate_answer
    - from: generate_answer
      to: critique_answer
    - from: critique_answer
      condition: tasks.examples.custom_subgraphs.task_executor.ShouldContinue
      path_map:
        END: END
        generate_answer: generate_answer

output_config:
    generator: tasks.examples.custom_subgraphs.task_executor.CustomSubgraphsOutputGenerator

    output_map:
      id:
        from: "id"
      conversation:
        from: "messages"
        transform: "build_conversation"
      metadata:
        from: "rephrased_text"
        transform: "build_metadata"