graph_config:
  nodes:
    persona_sampler:
      node_type: weighted_sampler
      attributes:
        num_turns:
          values: [2, 3, 4, 5]
        tone1:
          values: [professional, casual, friendly, inquisitive, formal, neutral, humorous, empathetic, enthusiastic, supportive, encouraging, optimistic, pessimistic, sarcastic, serious, urgent, relaxed, impatient, polite, apologetic, confident, uncertain, direct, indirect, assertive, passive, aggressive, rude, impolite]
        tone2:
          values: [professional, casual, friendly, inquisitive, formal, neutral, humorous, empathetic, enthusiastic, supportive, encouraging, optimistic, serious, relaxed, polite, apologetic, confident, direct, indirect, assertive, passive]
        persona1:
          values: [high school teacher, college professor, software engineer, software engineering manager, physicist, college student, high school student]
        persona2:
          values: [high school teacher, college professor, software engineer, software engineering manager, physicist, college student, high school student]

    paraphrase_question:
      node_type: llm
      output_keys: text
      prompt:
        - system: |
            Assume you are {persona1} persona.
            You are an assistant tasked with paraphrasing a user question. Make sure all the relevant details are preserved in the paraphrased question. Do NOT generate any conversational text and respond ONLY with the paraphrased question in the following format:
            "PARAPHRASED QUESTION: <question>"
        - user: |
            QUESTION: {p}. Write the program in python.
      model:
        name: gpt4o
        parameters:
          temperature: 0.1

  edges:
    - from: START
      to: persona_sampler
    - from: persona_sampler
      to: paraphrase_question
    - from: paraphrase_question
      to: END