data_config:
    source:
      type: "disk"
      file_path: "tasks/examples/subgraph_recipes/evol_instruct/test.json"
      file_format: "json"
      encoding: "utf-8"
graph_config:
  nodes:
    evol_text:
      node_type: subgraph
      subgraph: recipes.evol_instruct
    query_llm:
      node_type: llm
      prompt:
        - user: |
           {evolved_text}
      model:
        name: gpt-4o-mini
        parameters:
          temperature: 1.0

  edges:
    - from: START
      to: evol_text
    - from: evol_text
      to: query_llm
    - from: query_llm
      to: END


output_config:
  generator: tasks.examples.subgraph_recipes.evol_instruct.task_executor.EvolTextGenerator


