name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Just one lightweight setup job to warm the cache
  setup_sygra:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: make setup-dev

  # Run Formatting
  format:
    needs: setup_sygra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: make check-format
  # Run Linting
  lint:
    needs: setup_sygra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: make check-lint
  # Run Tests
  test:
    needs: setup_sygra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: make test
  # Build Docs
  docs_build:
    needs: setup_sygra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: make docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  # Deploy Docs
  deploy_docs:
    if: github.ref == 'refs/heads/main'
    needs: docs_build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
