name: MkDocs Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-include-markdown-plugin

      # Build MkDocs site
      - name: Build MkDocs site
        run: make docs
