name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Triggers when a new GitHub Tag is published eg: v1.2.3
  release:
    types: [published]  # Triggers when a new GitHub Release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.9-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}

      - name: Install dependencies
        run: make setup-dev

      - name: Set version from GitHub tag
        run: |
          # Extract tag like "v1.2.3" → "1.2.3"
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting version to $VERSION"
          # Update pyproject.toml version field
          sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml

      - name: Build package
        run: make build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          python -m twine upload --repository pypi dist/* --verbose
